"""
Slides renderer — produces a presentation resource JSON for the
Google Slides API.

The actual API push to `presentations.create` is parked until Quinn
+ Catherine sort Drive auth. The JSON output lands at
`/tmp/drifterbot-pickup/<run-dir>/slides-spec.json` for review.
"""

from __future__ import annotations

from typing import Any

from agents.driftbot.layout_catalog import LayoutName
from agents.driftbot.runner import AuditDraft

# D&A brand palette per BRANDING_PROFILES (drift-and-anchor):
DA_PRIMARY = '#160E33'   # deep navy/purple
DA_ACCENT = '#1470AF'    # brand blue (was '#C9A66B' — corrected 2026-07-22
                         # against the actual brand template)
DA_NEUTRAL_LIGHT = '#F5F5F5'
DA_NEUTRAL_DARK = '#313131'

# Provocation order
_PROVOCATIONS = [
    'Sea of Sameness',
    'Logo Bingo',
    'Audience Record Scratch',
    'Tone Deaf',
    'Brief In Context',
]


def _title_slide(draft: AuditDraft) -> dict:
    """Slide 1: Title slide (D&A cover layout)."""
    return {
        'slideId': 'slide-title',
        'layout': LayoutName.TITLE.value,
        'elements': [
            {
                'type': 'text',
                'placeholder': 'TITLE',
                'text': f"{draft.client.name}\nCompetitive Audit Draft",
            },
            {
                'type': 'text',
                'placeholder': 'SUBTITLE',
                'text': (
                    f"Generated by DrifterBot for Drift & Anchor · {draft.generated_at}"
                ),
            },
        ],
    }


def _exec_summary_slide(draft: AuditDraft) -> dict:
    """Slide 2: Executive summary (two-column layout)."""
    # Reuse the executive-summary synthesis from runner.
    from agents.driftbot.runner import _synthesize_executive_summary
    summary_text = _synthesize_executive_summary(draft.client, draft.competitors)
    return {
        'slideId': 'slide-exec-summary',
        'layout': LayoutName.TITLE_AND_TWO_COLUMNS.value,
        'elements': [
            {
                'type': 'text',
                'placeholder': 'TITLE',
                'text': 'Executive Summary',
            },
            {
                'type': 'text',
                'placeholder': 'BODY',
                'text': summary_text,
            },
        ],
    }


def _competitor_cards_slide(draft: AuditDraft) -> list[dict]:
    """One slide per competitor (standard body layout)."""
    slides = []
    for i, card_md in enumerate(draft.competitor_cards, start=1):
        slide_id = f'slide-comp-{i}'
        # Strip markdown header lines, keep body
        lines = card_md.splitlines()
        title = next(
            (line.replace('#', '').replace('*', '').strip()
             for line in lines if line.startswith('### ')),
            f'Competitor {i}',
        )
        body = '\n'.join(line for line in lines if not line.startswith('#'))
        slides.append({
            'slideId': slide_id,
            'layout': LayoutName.TITLE_AND_BODY.value,
            'elements': [
                {
                    'type': 'text',
                    'placeholder': 'TITLE',
                    'text': title,
                },
                {
                    'type': 'text',
                    'placeholder': 'BODY',
                    'text': body.strip(),
                },
            ],
        })
    return slides


def _provocation_slides(draft: AuditDraft) -> list[dict]:
    """One slide per Provocation chapter (standard body layout)."""
    slides = []
    for i, chapter_md in enumerate(draft.provocation_chapters, start=1):
        prov_name = _PROVOCATIONS[i - 1] if (i - 1) < len(_PROVOCATIONS) else f'Provocation {i}'
        slide_id = f'slide-prov-{i}'
        # Body is everything except top-level title
        body = '\n'.join(
            line for line in chapter_md.splitlines()
            if not line.startswith('# ')
        ).strip()
        slides.append({
            'slideId': slide_id,
            'layout': LayoutName.TITLE_AND_BODY.value,
            'elements': [
                {
                    'type': 'text',
                    'placeholder': 'TITLE',
                    'text': f'{prov_name} — {draft.client.name}',
                },
                {
                    'type': 'text',
                    'placeholder': 'BODY',
                    'text': body,
                },
            ],
        })
    return slides


def render_slides_spec(draft: AuditDraft, payload: dict) -> dict[str, Any]:
    """Build a presentation resource JSON for the Google Slides API.

    Output is the `presentation` shape consumed by
    `presentations.create()` + `presentations.batchUpdate()`.
    """
    slides = (
        [_title_slide(draft), _exec_summary_slide(draft)]
        + _competitor_cards_slide(draft)
        + _provocation_slides(draft)
    )

    # Folder naming convention (per Quinn): clients/<name>-<audit_id>-<date>/
    # Stash on the JSON for the parked Drive-write step.
    folder_name = f"clients/{draft.client.id}-{draft.audit_id}"

    return {
        'title': f"{draft.client.name} — Competitive Audit Draft",
        'locale': 'en_US',
        'slides': slides,
        'theme': {
            'primary': DA_PRIMARY,
            'accent': DA_ACCENT,
            'neutral_light': DA_NEUTRAL_LIGHT,
            'neutral_dark': DA_NEUTRAL_DARK,
        },
        '_dandA_meta': {
            'audit_id': draft.audit_id,
            'client': draft.client.name,
            'requested_at': payload.get('requested_at'),
            'social_scans': payload.get('social_scans', []),
            'context_drive_links': payload.get('context_drive_links', []),
            'folder_name': folder_name,
        },
    }
