server {
    listen [::]:443 ssl;
    listen 443 ssl;
    server_name psifunction.com www.psifunction.com;

    ssl_certificate /etc/letsencrypt/live/psifunction.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/psifunction.com/privkey.pem;

    include /etc/letsencrypt/options-ssl-nginx.conf;
    include /etc/nginx/snippets/hardening-common.conf;
    include /etc/nginx/snippets/security-headers.conf;
    add_header Strict-Transport-Security "max-age=86400" always;

    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    access_log /var/log/nginx/consulting-site-production.access.log;
    error_log  /var/log/nginx/consulting-site-production.error.log warn;

    location /static/ {
        if ($request_method !~ ^(GET|HEAD)$) {
            return 405;
        }

        alias /opt/consulting-site/production/current/app/static/;
        expires 1h;
        add_header Cache-Control "public";
    }

    location /uploads/ {
        if ($request_method !~ ^(GET|HEAD)$) {
            return 405;
        }

        alias /opt/consulting-site/production/shared/uploads/;
        expires 1h;
        add_header Cache-Control "public";
    }

    location = /health {
        access_log off;
        allow all;

        if ($request_method !~ ^(GET|HEAD)$) {
            return 405;
        }

        proxy_pass http://unix:/opt/consulting-site/production/shared/run/gunicorn.sock;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass http://unix:/opt/consulting-site/production/shared/run/gunicorn.sock;
        
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_read_timeout 60s;
        proxy_connect_timeout 5s;
        proxy_send_timeout 60s;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name psifunction.com www.psifunction.com;
    return 301 https://$host$request_uri;
}