server {
    server_name testing.psifunction.com;

    client_max_body_size 20m;

    access_log /var/log/nginx/consulting-site-testing.access.log;
    error_log  /var/log/nginx/consulting-site-testing.error.log warn;

    location /static/ {
        alias /opt/consulting-site/testing/current/app/static/;
        expires 1h;
        add_header Cache-Control "public";
    }

    location /uploads/ {
        alias /opt/consulting-site/testing/shared/uploads/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/opt/consulting-site/testing/shared/run/gunicorn.sock;
    }
}
