"""add taxonomy and work item models

Revision ID: 8d63edc201fd
Revises: a1b2c3d4e5f6
Create Date: 2026-06-03 08:32:39.256115

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8d63edc201fd'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxonomy_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('axis', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('taxonomy_tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taxonomy_tag_axis'), ['axis'], unique=False)

    op.create_table('work_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('is_projected', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column(
        'created_at', sa.DateTime(),
        server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True,
    ),
    sa.Column(
        'updated_at', sa.DateTime(),
        server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True,
    ),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_item_tags',
    sa.Column('work_item_id', sa.Integer(), nullable=False),
    sa.Column('taxonomy_tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['taxonomy_tag_id'], ['taxonomy_tag.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('work_item_id', 'taxonomy_tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_item_tags')
    op.drop_table('work_item')
    with op.batch_alter_table('taxonomy_tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_taxonomy_tag_axis'))

    op.drop_table('taxonomy_tag')
    # ### end Alembic commands ###
