"""Add client font fields

Revision ID: 90c96eb9c0d6
Revises: f077998165fc
Create Date: 2026-04-15 10:36:16.549257

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '90c96eb9c0d6'
down_revision = 'f077998165fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('font_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('font_display', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('font_display')
        batch_op.drop_column('font_url')

    # ### end Alembic commands ###
