"""
Unit tests for slides_client wire translation (intent spec ->
Google Slides API batchUpdate requests).

These run without any network access — they're pure-Python checks on
the request shape that DriveSaveStrategy.save() will hand to the API.

The whole point is: catch a malformed batchUpdate body before we ever
spend a Drive API call on it. Google's API returns a generic 400 with
no great diagnostics for this surface, so the test asserts the wire
shape directly.
"""

from __future__ import annotations

import json

from agents.driftbot.slides_client import (
    _LAYOUT_POSITIONS,
    SLIDE_H_EMU,
    SLIDE_W_EMU,
    _insert_text_request,
    _intent_slide_to_wire_requests,
    _shape_request,
    build_batch_update_requests,
)


def test_shape_request_has_required_fields():
    req = _shape_request('foo', 'slide-1', 'hello', 100, 200, 1000, 2000)
    assert 'createShape' in req
    cs = req['createShape']
    assert cs['objectId'] == 'foo'
    assert cs['shapeType'] == 'TEXT_BOX'
    assert cs['elementProperties']['pageObjectId'] == 'slide-1'
    assert cs['elementProperties']['transform']['translateX'] == 100
    assert cs['elementProperties']['transform']['translateY'] == 200
    assert cs['elementProperties']['size']['width']['magnitude'] == 1000
    assert cs['elementProperties']['size']['height']['magnitude'] == 2000
    assert cs['elementProperties']['transform']['unit'] == 'EMU'


def test_insert_text_request_has_required_fields():
    req = _insert_text_request('foo', 'bar')
    assert req == {
        'insertText': {'objectId': 'foo', 'insertionIndex': 0, 'text': 'bar'},
    }


def test_object_id_format_compliance():
    """Per Google: objectIds must start with a letter, alphanumeric/underscore/hyphen.
    Our intent slideIds like 'slide-title' already comply.
    """
    import re
    pattern = re.compile(r'^[a-zA-Z][a-zA-Z0-9_-]*$')
    for slide_id in ['slide-title', 'slide-exec-summary', 'slide-comp-1', 'slide-prov-5']:
        assert pattern.match(slide_id), f"objectId must match pattern: {slide_id}"


def test_title_slide_translates_to_create_plus_two_text_boxes():
    """Standard slide from renderer: TITLE layout, title + subtitle."""
    slide = {
        'slideId': 'slide-title',
        'layout': 'TITLE',
        'elements': [
            {'type': 'text', 'placeholder': 'TITLE', 'text': 'Acme — Competitive Audit Draft'},
            {'type': 'text', 'placeholder': 'SUBTITLE', 'text': 'Generated by DrifterBot'},
        ],
    }
    reqs = _intent_slide_to_wire_requests(slide, insertion_index=0)
    assert len(reqs) == 1 + 4  # createSlide + 2*(createShape + insertText)
    # First request creates the slide with the right reference
    assert reqs[0]['createSlide']['objectId'] == 'slide-title'
    assert reqs[0]['createSlide']['insertionIndex'] == 0
    assert reqs[0]['createSlide']['slideLayoutReference']['predefinedLayout'] == 'TITLE'
    # Title element
    title_shape = reqs[1]
    assert title_shape['createShape']['objectId'] == 'slide-title_title'
    assert title_shape['createShape']['elementProperties']['pageObjectId'] == 'slide-title'
    assert title_shape['createShape']['elementProperties']['size']['width']['magnitude'] == _LAYOUT_POSITIONS['TITLE']['TITLE'][2]  # noqa: E501
    assert reqs[2]['insertText']['text'] == 'Acme — Competitive Audit Draft'
    assert reqs[2]['insertText']['objectId'] == 'slide-title_title'
    # Subtitle element
    sub_shape = reqs[3]
    assert sub_shape['createShape']['objectId'] == 'slide-title_subtitle'
    assert sub_shape['createShape']['elementProperties']['pageObjectId'] == 'slide-title'
    assert reqs[4]['insertText']['text'] == 'Generated by DrifterBot'
    assert reqs[4]['insertText']['objectId'] == 'slide-title_subtitle'


def test_title_and_body_layout_uses_body_placeholder():
    slide = {
        'slideId': 'slide-comp-1',
        'layout': 'TITLE_AND_BODY',
        'elements': [
            {'type': 'text', 'placeholder': 'TITLE', 'text': 'Competitor One'},
            {'type': 'text', 'placeholder': 'BODY', 'text': 'Some long body text'},
        ],
    }
    reqs = _intent_slide_to_wire_requests(slide, insertion_index=2)
    assert reqs[0]['createSlide']['insertionIndex'] == 2
    # body element is the 4th request (index 3 = insertText for body)
    # reqs[0] = createSlide, reqs[1] = title createShape, reqs[2] = title insertText,
    # reqs[3] = body createShape, reqs[4] = body insertText
    assert reqs[4]['insertText']['objectId'] == 'slide-comp-1_body'
    assert reqs[4]['insertText']['text'] == 'Some long body text'
    assert reqs[3]['createShape']['objectId'] == 'slide-comp-1_body'


def test_unknown_layout_falls_back_to_title_and_body():
    """Renderer future-proofing: a 'HERO' layout shouldn't break save."""
    slide = {
        'slideId': 'slide-x',
        'layout': 'HERO_NOT_REAL',
        'elements': [
            {'type': 'text', 'placeholder': 'TITLE', 'text': 'Title'},
            {'type': 'text', 'placeholder': 'BODY', 'text': 'Body'},
        ],
    }
    reqs = _intent_slide_to_wire_requests(slide, insertion_index=0)
    assert reqs[0]['createSlide']['slideLayoutReference']['predefinedLayout'] == 'TITLE_AND_BODY'


def test_unknown_placeholder_falls_back_to_body_position():
    slide = {
        'slideId': 'slide-y',
        'layout': 'TITLE_AND_BODY',
        'elements': [
            {'type': 'text', 'placeholder': 'CAPTION', 'text': 'caption'},
        ],
    }
    reqs = _intent_slide_to_wire_requests(slide, insertion_index=0)
    # CAPTION not in TITLE_AND_BODY positions — should fall back to body sized box
    shape_req = reqs[1]['createShape']
    body_w = _LAYOUT_POSITIONS['TITLE_AND_BODY']['BODY'][2]
    assert shape_req['elementProperties']['size']['width']['magnitude'] == body_w


def test_non_text_elements_are_skipped():
    """Image / video / shape elements are out of scope for MVP save."""
    slide = {
        'slideId': 'slide-z',
        'layout': 'TITLE_AND_BODY',
        'elements': [
            {'type': 'text', 'placeholder': 'TITLE', 'text': 'T'},
            {'type': 'image', 'src': 'http://example.com/x.png'},  # should skip
            {'type': 'text', 'placeholder': 'BODY', 'text': 'B'},
        ],
    }
    reqs = _intent_slide_to_wire_requests(slide, insertion_index=0)
    # createSlide + 2 createShapes + 2 insertTexts = 5
    assert len(reqs) == 5


def test_build_batch_update_requests_handles_full_deck():
    """End-to-end wire build against the renderer output structure."""
    from agents.driftbot.renderer_slides import render_slides_spec
    from agents.driftbot.runner import (
        AuditDraft,
        ClientConfig,
        CompetitorConfig,
    )

    client = ClientConfig(
        id='hallmark',
        name='Hallmark Health Care',
        category='healthcare staffing',
        audiences=['hospital admin'],
        positioning_inputs={},
    )
    competitors = [
        CompetitorConfig(
            id=f'comp{i}', name=f'Competitor {i}',
            category_position='staffing',
            summary='blah',
        )
        for i in range(1, 6)
    ]
    draft = AuditDraft(
        audit_id='abc12345',
        client=client,
        competitors=competitors,
        competitor_cards=[f'### Competitor {i}\nBody' for i in range(1, 6)],
        provocation_chapters=['## Prov 1\nbody'] * 5,
        generated_at='2026-07-21T09:00:00Z',
    )
    spec = render_slides_spec(draft, payload={})

    requests = build_batch_update_requests(spec['slides'])
    # 12 slides, each yields createSlide + 2*(createShape + insertText) = 5 reqs
    # Total: 12 * 5 = 60 requests
    assert len(requests) == 60, f"expected 60 requests, got {len(requests)}"
    # JSON-serializable (Google's API requires plain JSON)
    json.dumps(requests)
    # Every createSlide has an insertionIndex set
    for req in requests:
        if 'createSlide' in req:
            assert 'insertionIndex' in req['createSlide']


def test_shape_positions_within_slide_bounds():
    """All elements must fit within the 16:9 slide (12.192M x 6.858M EMU)."""
    spec = {
        'slideId': 'test-slide',
        'layout': 'TITLE_AND_BODY',
        'elements': [
            {'type': 'text', 'placeholder': 'TITLE', 'text': 'T'},
            {'type': 'text', 'placeholder': 'BODY', 'text': 'B'},
        ],
    }
    reqs = _intent_slide_to_wire_requests(spec, insertion_index=0)
    for req in reqs:
        if 'createShape' not in req:
            continue
        size = req['createShape']['elementProperties']['size']
        x = req['createShape']['elementProperties']['transform']['translateX']
        y = req['createShape']['elementProperties']['transform']['translateY']
        w = size['width']['magnitude']
        h = size['height']['magnitude']
        assert x >= 0, f"x={x} negative"
        assert y >= 0, f"y={y} negative"
        assert x + w <= SLIDE_W_EMU, f"x+w={x+w} exceeds slide width {SLIDE_W_EMU}"
        assert y + h <= SLIDE_H_EMU, f"y+h={y+h} exceeds slide height {SLIDE_H_EMU}"
